import "Windows.Media.idl";

#include <sdkddkver.h>

namespace CoreMFSource
{
	[version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
	runtimeclass HDCoreByteStreamHandler
	{
		[default] interface Windows.Media.IMediaExtension;
	}
}