import "Windows.Media.idl";

#include <sdkddkver.h>

namespace MultipartStreamMatroska
{
	[version(NTDDI_WIN8), activatable(NTDDI_WIN8)]
	runtimeclass UrlHandler
	{
		[default] interface Windows.Media.IMediaExtension;
	}
}
